server.port=9292
spring.application.name=spring-ai-mcp-client

# ===============================
# OpenAI / Model
# ===============================
spring.ai.openai.api-key=${OPENAI_API_KEY}

# ===============================
# Spring AI MCP Client (HTTP)
# ===============================
spring.ai.mcp.client.streamable-http.connections.demoServer.url=http://127.0.0.1:9191