server.port=9191
spring.application.name=openai-demo
spring.ai.openai.api-key=${OPENAI_API_KEY}

spring.ai.vectorstore.pinecone.api-key=${PINECONE_API_KEY}
spring.ai.vectorstore.pinecone.index-name=springaidemo
spring.servlet.multipart.max-file-size=10MB
