<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.company</groupId>
        <artifactId>udemy</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>author-bharath</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>udemy-bharath-claude-code-for-java-spring-boot</module>
        <module>udemy-bharath-core-java-made-easy</module>
        <module>udemy-bharath-devops-tools-and-aws</module>
        <module>udemy-bharath-java-design-patterns</module>
        <module>udemy-bharath-java-interview-help</module>
        <module>udemy-bharath-java-logical-programs-data-structure</module>
        <module>udemy-bharath-java-web-services</module>
        <module>udemy-bharath-java-web-services-2-soap-rest-security</module>
        <module>udemy-bharath-jms-fundamentals</module>
        <module>udemy-bharath-junit-and-mockito</module>
        <module>udemy-bharath-kafka-fundamentals</module>
        <module>udemy-bharath-project-development-using-spring-boot</module>
        <module>udemy-bharath-rest-api-using-spring-data-rest</module>
        <module>udemy-bharath-spring-ai</module>
        <module>udemy-bharath-spring-boot-fundamentals</module>
        <module>udemy-bharath-spring-cloud-fundamentals</module>
        <module>udemy-bharath-spring-data-jpa-using-hibernate</module>
        <module>udemy-bharath-spring-framework-in-easy-steps</module>
        <module>udemy-bharath-spring-security-fundamentals</module>
    </modules>

</project>